version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nodeless-api
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nodeless-api-network
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    networks:
      - nodeless-api-network
    ports:
      - "6379:6379"

networks:
  nodeless-api-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local

  redis_data:
    driver: local